"""GitHub Integration component for the Bedrock IaC Agent.

Manages all interactions with Azure GitHub repository including authentication,
cloning, branching, committing, pushing, and Pull Request creation.
"""

import logging
import os
import tempfile
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import git
from github import Github, GithubException
from github.Repository import Repository as GithubRepository

from bedrock_iac_agent.audit_logger import AuditLogger
from bedrock_iac_agent.errors import (
    AuthenticationError,
    NetworkError,
    RepositoryError,
    RetryStrategy,
    ThrottlingError,
    ValidationError,
)
from bedrock_iac_agent.models import (
    FileChange,
    GitHubCredentials,
    PullRequest,
    PullRequestDetails,
)

logger = logging.getLogger(__name__)


# Re-export for backwards compatibility so existing imports from this module
# continue to work without changes.
__all__ = [
    "AuthenticationError",
    "GitHubIntegration",
    "NetworkError",
    "RepositoryError",
    "RetryStrategy",
    "ThrottlingError",
    "ValidationError",
]


# ---------------------------------------------------------------------------
# Pull Request template
# ---------------------------------------------------------------------------

_PR_TEMPLATE = """\
## Infrastructure Change Request

**Resource Type**: {resource_type}
**Environment**: {environment}
**Requested By**: {user_id}
**Timestamp**: {timestamp}

### Configuration Parameters
{parameter_table}

### Changes
- Modified: `environments/{environment}/terraform.tfvars`

### Justification
{justification}

### Review Checklist
- [ ] Parameters match requirements
- [ ] Naming conventions applied
- [ ] Security settings preserved
- [ ] Environment is correct

---
Generated by Bedrock IaC Agent
Conversation ID: {conversation_id}
"""


def _build_parameter_table(metadata: Dict[str, Any]) -> str:
    """Build a Markdown table from the parameters stored in PR metadata."""
    parameters: Dict[str, Any] = metadata.get("parameters", {})
    if not parameters:
        return "_No parameters provided._"

    rows = ["| Parameter | Value |", "| --- | --- |"]
    for key, value in parameters.items():
        rows.append(f"| `{key}` | `{value}` |")
    return "\n".join(rows)


def _render_pr_body(pr_details: PullRequestDetails) -> str:
    """Render the PR description from the template and PullRequestDetails."""
    meta = pr_details.metadata or {}
    resource_type = meta.get("resource_type", "N/A")
    environment = meta.get("environment", "N/A")
    user_id = meta.get("user_id", "N/A")
    timestamp = meta.get("timestamp", datetime.now(timezone.utc).isoformat())
    justification = meta.get("justification", pr_details.description or "N/A")
    conversation_id = meta.get("conversation_id", "N/A")
    parameter_table = _build_parameter_table(meta)

    return _PR_TEMPLATE.format(
        resource_type=resource_type,
        environment=environment,
        user_id=user_id,
        timestamp=timestamp,
        parameter_table=parameter_table,
        justification=justification,
        conversation_id=conversation_id,
    )


# ---------------------------------------------------------------------------
# GitHubIntegration
# ---------------------------------------------------------------------------


class GitHubIntegration:
    """Manages all GitHub operations for the Bedrock IaC Agent.

    Uses PyGithub for GitHub API interactions and GitPython for local git
    operations (clone, branch, commit, push).

    Args:
        credentials: GitHub credentials (token, organization, repository).
        audit_logger: Optional AuditLogger instance for structured logging.
        retry_strategy: Optional RetryStrategy; defaults to 3 attempts with
            exponential backoff.
        work_dir: Optional base directory for cloned repositories.  When
            *None* a temporary directory is created automatically.
    """

    def __init__(
        self,
        credentials: GitHubCredentials,
        audit_logger: Optional[AuditLogger] = None,
        retry_strategy: Optional[RetryStrategy] = None,
        work_dir: Optional[str] = None,
    ) -> None:
        self.credentials = credentials
        self.audit_logger = audit_logger or AuditLogger()
        self.retry_strategy = retry_strategy or RetryStrategy()
        self.work_dir = work_dir
        self._github_client: Optional[Github] = None
        self._github_repo: Optional[GithubRepository] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def authenticate(self) -> bool:
        """Authenticate with GitHub using the stored credentials.

        Returns:
            True on success.

        Raises:
            AuthenticationError: If the token is invalid or lacks permissions.
        """
        try:
            client = Github(self.credentials.token)
            # Trigger an API call to validate the token
            user = client.get_user()
            _ = user.login  # forces the lazy request

            # Verify access to the target repository
            repo_full_name = f"{self.credentials.organization}/{self.credentials.repository}"
            self._github_repo = client.get_repo(repo_full_name)
            self._github_client = client

            logger.info(
                "Authenticated with GitHub as %s, repo: %s",
                user.login,
                repo_full_name,
            )
            return True

        except GithubException as exc:
            auth_error = AuthenticationError(
                f"GitHub authentication failed: {exc.data.get('message', str(exc))}. "
                "Please verify your GitHub token and ensure it has the required permissions."
            )
            self.audit_logger.log_error(
                auth_error,
                {"operation": "authenticate", "organization": self.credentials.organization},
                error_code="AUTH_FAILED",
            )
            raise auth_error from exc
        except Exception as exc:
            auth_error = AuthenticationError(
                f"GitHub authentication failed: {exc}. "
                "Please verify your GitHub token and network connectivity."
            )
            self.audit_logger.log_error(
                auth_error,
                {"operation": "authenticate"},
                error_code="AUTH_FAILED",
            )
            raise auth_error from exc

    def clone_repository(self, repo_url: str, local_path: Optional[str] = None) -> git.Repo:
        """Clone the base repository to a local path.

        Args:
            repo_url: HTTPS or SSH URL of the repository to clone.
            local_path: Local directory to clone into.  When *None* a
                temporary directory is created inside ``self.work_dir``.

        Returns:
            A :class:`git.Repo` instance for the cloned repository.

        Raises:
            NetworkError: If the clone fails after all retry attempts.
        """
        if local_path is None:
            base = self.work_dir or tempfile.gettempdir()
            local_path = tempfile.mkdtemp(dir=base, prefix="iac-agent-")

        # Inject token into HTTPS URL for authentication
        authenticated_url = self._inject_token(repo_url)

        return self._with_retry(
            lambda: self._do_clone(authenticated_url, local_path),
            operation="clone_repository",
        )

    def create_branch(self, repo: git.Repo, branch_name: str) -> git.Head:
        """Create a new branch in the local repository.

        Args:
            repo: Local git repository.
            branch_name: Name for the new branch.  Should follow the pattern
                ``iac-agent/{resource-type}/{environment}/{timestamp}``.

        Returns:
            The newly created :class:`git.Head` branch reference.

        Raises:
            RepositoryError: If the branch already exists or cannot be created.
        """
        if not branch_name:
            raise ValidationError("branch_name must not be empty")

        try:
            branch = repo.create_head(branch_name)
            branch.checkout()
            logger.info("Created and checked out branch: %s", branch_name)
            return branch
        except git.GitCommandError as exc:
            repo_error = RepositoryError(
                f"Failed to create branch '{branch_name}': {exc}. "
                "The branch may already exist or you may lack the required permissions."
            )
            self.audit_logger.log_error(
                repo_error,
                {"operation": "create_branch", "branch_name": branch_name},
                error_code="BRANCH_CREATION_FAILED",
            )
            raise repo_error from exc

    def commit_changes(
        self,
        repo: git.Repo,
        files: List[FileChange],
        commit_message: str,
    ) -> git.Commit:
        """Write file changes to disk and create a git commit.

        Args:
            repo: Local git repository.
            files: List of :class:`~bedrock_iac_agent.models.FileChange` objects
                describing the files to add/modify/delete.
            commit_message: Commit message string.

        Returns:
            The created :class:`git.Commit` object.

        Raises:
            RepositoryError: If the commit fails.
            ValidationError: If *files* is empty.
        """
        if not files:
            raise ValidationError("At least one FileChange is required to commit")

        try:
            repo_root = repo.working_tree_dir
            assert repo_root is not None, "Repository has no working tree"

            for file_change in files:
                abs_path = os.path.join(repo_root, file_change.file_path)
                os.makedirs(os.path.dirname(abs_path), exist_ok=True)

                if file_change.operation in ("add", "modify"):
                    with open(abs_path, "w", encoding="utf-8") as fh:
                        fh.write(file_change.content)
                    repo.index.add([file_change.file_path])
                elif file_change.operation == "delete":
                    if os.path.exists(abs_path):
                        os.remove(abs_path)
                    repo.index.remove([file_change.file_path])

            commit = repo.index.commit(commit_message)
            logger.info("Committed %d file(s): %s", len(files), commit.hexsha[:8])
            return commit

        except git.GitCommandError as exc:
            repo_error = RepositoryError(
                f"Failed to commit changes: {exc}. "
                "Please verify the repository state and try again."
            )
            self.audit_logger.log_error(
                repo_error,
                {"operation": "commit_changes", "file_count": len(files)},
                error_code="COMMIT_FAILED",
            )
            raise repo_error from exc

    def push_branch(self, repo: git.Repo, branch: git.Head) -> bool:
        """Push a local branch to the remote repository.

        Args:
            repo: Local git repository.
            branch: The branch to push.

        Returns:
            True on success.

        Raises:
            NetworkError: If the push fails after all retry attempts.
        """
        return self._with_retry(
            lambda: self._do_push(repo, branch),
            operation="push_branch",
        )

    def create_pull_request(
        self,
        branch: git.Head,
        pr_details: PullRequestDetails,
    ) -> PullRequest:
        """Create a Pull Request on GitHub.

        Args:
            branch: The source branch that was pushed.
            pr_details: Details for the Pull Request (title, description,
                target branch, labels, reviewers, metadata).

        Returns:
            A :class:`~bedrock_iac_agent.models.PullRequest` dataclass with
            the PR URL, number, branch name, and creation timestamp.

        Raises:
            AuthenticationError: If not authenticated.
            NetworkError: If the API call fails after all retry attempts.
            RepositoryError: If the PR cannot be created (e.g. already exists).
        """
        if self._github_repo is None:
            raise AuthenticationError(
                "Not authenticated. Call authenticate() before create_pull_request()."
            )

        body = _render_pr_body(pr_details)

        return self._with_retry(
            lambda: self._do_create_pr(pr_details, body),
            operation="create_pull_request",
        )

    # ------------------------------------------------------------------
    # Branch naming helper
    # ------------------------------------------------------------------

    @staticmethod
    def build_branch_name(
        resource_type: str,
        environment: str,
        timestamp: Optional[str] = None,
    ) -> str:
        """Build a branch name following the ``iac-agent/{resource-type}/{environment}/{timestamp}`` pattern.

        Args:
            resource_type: AWS resource type slug (e.g. ``s3_bucket``).
            environment: Target environment (e.g. ``dev``, ``prod``).
            timestamp: Optional timestamp string.  Defaults to the current UTC
                time formatted as ``YYYYMMDD-HHMMSS``.

        Returns:
            A branch name string.
        """
        if not resource_type:
            raise ValidationError("resource_type must not be empty")
        if not environment:
            raise ValidationError("environment must not be empty")

        if timestamp is None:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

        # Normalise: replace underscores with hyphens for URL-friendly names
        resource_slug = resource_type.replace("_", "-").lower()
        env_slug = environment.replace("_", "-").lower()

        return f"iac-agent/{resource_slug}/{env_slug}/{timestamp}"

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _inject_token(self, url: str) -> str:
        """Inject the GitHub token into an HTTPS URL for authentication."""
        if url.startswith("https://") and self.credentials.token:
            # https://token@github.com/org/repo.git
            return url.replace("https://", f"https://{self.credentials.token}@", 1)
        return url

    def _do_clone(self, url: str, local_path: str) -> git.Repo:
        """Perform the actual git clone operation."""
        try:
            repo = git.Repo.clone_from(url, local_path)
            logger.info("Cloned repository to %s", local_path)
            return repo
        except git.GitCommandError as exc:
            network_error = NetworkError(
                f"Failed to clone repository: {exc}. "
                "Please verify the repository URL and your network connectivity."
            )
            self.audit_logger.log_error(
                network_error,
                {"operation": "clone_repository", "local_path": local_path},
                error_code="CLONE_FAILED",
            )
            raise network_error from exc

    def _do_push(self, repo: git.Repo, branch: git.Head) -> bool:
        """Perform the actual git push operation."""
        try:
            origin = repo.remote("origin")
            push_info = origin.push(refspec=f"{branch.name}:{branch.name}")
            for info in push_info:
                if info.flags & git.remote.PushInfo.ERROR:
                    network_error = NetworkError(
                        f"Push failed: {info.summary}. "
                        "Please verify your repository permissions and network connectivity."
                    )
                    self.audit_logger.log_error(
                        network_error,
                        {"operation": "push_branch", "branch": branch.name},
                        error_code="PUSH_FAILED",
                    )
                    raise network_error
            logger.info("Pushed branch '%s' to remote", branch.name)
            return True
        except git.GitCommandError as exc:
            network_error = NetworkError(
                f"Failed to push branch: {exc}. "
                "Please verify your repository permissions and network connectivity."
            )
            self.audit_logger.log_error(
                network_error,
                {"operation": "push_branch", "branch": branch.name},
                error_code="PUSH_FAILED",
            )
            raise network_error from exc

    def _do_create_pr(
        self,
        pr_details: PullRequestDetails,
        body: str,
    ) -> PullRequest:
        """Perform the actual GitHub API call to create a Pull Request."""
        assert self._github_repo is not None

        try:
            gh_pr = self._github_repo.create_pull(
                title=pr_details.title,
                body=body,
                head=pr_details.source_branch,
                base=pr_details.target_branch,
            )

            # Apply labels (best-effort – labels must exist in the repo)
            if pr_details.labels:
                try:
                    gh_pr.set_labels(*pr_details.labels)
                except GithubException as exc:
                    logger.warning("Could not apply labels to PR: %s", exc)

            # Request reviewers (best-effort)
            if pr_details.reviewers:
                try:
                    gh_pr.create_review_request(reviewers=pr_details.reviewers)
                except GithubException as exc:
                    logger.warning("Could not request reviewers for PR: %s", exc)

            pr = PullRequest(
                url=gh_pr.html_url,
                number=gh_pr.number,
                branch_name=pr_details.source_branch,
                created_at=datetime.now(timezone.utc),
            )

            self.audit_logger.log_pull_request(
                pr_url=pr.url,
                request_id=pr_details.metadata.get("request_id", ""),
            )
            logger.info("Created PR #%d: %s", pr.number, pr.url)
            return pr

        except GithubException as exc:
            # Re-raise transient server errors (5xx) directly so _with_retry can
            # apply exponential-backoff retry logic (Requirement 12.2).
            if exc.status >= 500:
                raise
            repo_error = RepositoryError(
                f"Failed to create Pull Request: {exc.data.get('message', str(exc))}. "
                "Please verify the repository exists and you have write permissions."
            )
            self.audit_logger.log_error(
                repo_error,
                {
                    "operation": "create_pull_request",
                    "source_branch": pr_details.source_branch,
                    "target_branch": pr_details.target_branch,
                },
                error_code="PR_CREATION_FAILED",
            )
            raise repo_error from exc

    def _with_retry(self, operation_fn: Any, operation: str) -> Any:
        """Execute *operation_fn* with exponential-backoff retry.

        Args:
            operation_fn: A zero-argument callable that performs the operation.
            operation: Human-readable name used in log messages.

        Returns:
            The return value of *operation_fn* on success.

        Raises:
            The last exception raised by *operation_fn* if all attempts fail.
        """
        last_exc: Optional[Exception] = None
        for attempt in range(self.retry_strategy.max_attempts):
            try:
                return operation_fn()
            except Exception as exc:
                last_exc = exc
                if self.retry_strategy.should_retry(exc, attempt + 1):
                    delay = self.retry_strategy.get_delay(attempt)
                    logger.warning(
                        "Operation '%s' failed (attempt %d/%d): %s. Retrying in %.1fs…",
                        operation,
                        attempt + 1,
                        self.retry_strategy.max_attempts,
                        exc,
                        delay,
                    )
                    time.sleep(delay)
                else:
                    raise

        # All attempts exhausted
        raise last_exc  # type: ignore[misc]
