# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-apigw-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : api_gateway
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/api_gateway
# Module ver  : 1.0.0
# =============================================================================
api_name = "mycompany-rest-api-dev"  # Name of the API Gateway
endpoint_type = "REGIONAL"  # API endpoint type (REGIONAL, EDGE, PRIVATE)
environment = "dev"  # Deployment environment

# --- Security parameters (managed by Golden Module) ---
enable_cloudwatch_metrics = true  # Enable detailed CloudWatch metrics
enable_waf = true  # Enable AWS WAF integration
