# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-apigw-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : api_gateway
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/api_gateway
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
name = "mycompany-rest-api-dev"  # Name of the api_gateway
