# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-cw-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : cloudwatch_log_group
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/cloudwatch_log_group
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
name = "mycompany-app-logs-dev"  # Name of the cloudwatch_log_group
