# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-dynamo-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : dynamodb_table
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/dynamodb_table
# Module ver  : 1.0.0
# =============================================================================
billing_mode = "PAY_PER_REQUEST"  # Billing mode (PAY_PER_REQUEST or PROVISIONED)
environment = "dev"  # Deployment environment
hash_key = "id"  # Partition key name
table_name = "mycompany-sessions-dev"  # Name of the DynamoDB table

# --- Security parameters (managed by Golden Module) ---
point_in_time_recovery = true  # Enable point-in-time recovery
server_side_encryption = true  # Enable server-side encryption
