# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-dynamo-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : dynamodb_table
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/dynamodb_table
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
name = "mycompany-sessions-dev"  # Name of the dynamodb_table
