# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-ec2-prod
# Generated at: 2024-01-15T10:30:00Z
# Resource    : ec2_instance
# Environment : prod
# Justification: Snapshot test request
# Module path : modules/ec2_instance
# Module ver  : 1.0.0
# =============================================================================
ami_id = "latest-amazon-linux-2"  # AMI ID for the instance
environment = "prod"  # Deployment environment
instance_name = "mycompany-web-server-prod"  # Name of the EC2 instance
instance_type = "t3.large"  # EC2 instance type (e.g., t3.micro)

# --- Security parameters (managed by Golden Module) ---
enable_detailed_monitoring = true  # Enable detailed CloudWatch monitoring
