# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-iam-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : iam_role
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/iam_role
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
max_session_duration = 3600  # Maximum session duration in seconds
role_name = "mycompany-lambda-exec-dev"  # Name of the IAM role
trusted_services = ["lambda.amazonaws.com"]  # AWS services that can assume this role

# --- Security parameters (managed by Golden Module) ---
enforce_least_privilege = true  # Enforce least privilege policy review
require_mfa = true  # Require MFA for role assumption
