# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-iam-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : iam_role
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/iam_role
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
name = "mycompany-lambda-exec-dev"  # Name of the iam_role
