# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-lambda-prod
# Generated at: 2024-01-15T10:30:00Z
# Resource    : lambda_function
# Environment : prod
# Justification: Snapshot test request
# Module path : modules/lambda_function
# Module ver  : 1.0.0
# =============================================================================
environment = "prod"  # Deployment environment
function_name = "mycompany-data-processor-prod"  # Name of the Lambda function
memory_size = 512  # Memory size in MB
runtime = "python3.11"  # Lambda runtime (python3.11, nodejs18.x, etc.)
timeout = 60  # Timeout in seconds

# --- Security parameters (managed by Golden Module) ---
enable_cloudwatch_logs = true  # Enable CloudWatch logging
