# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-rds-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : rds_database
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/rds_database
# Module ver  : 1.0.0
# =============================================================================
db_name = "mycompany-appdb-dev"  # Database name
engine = "postgres"  # Database engine (postgres, mysql, etc.)
environment = "dev"  # Deployment environment
instance_class = "db.t3.micro"  # RDS instance class

# --- Security parameters (managed by Golden Module) ---
backup_retention_period = 7  # Backup retention period in days
storage_encrypted = true  # Enable storage encryption
