# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-s3-prod
# Generated at: 2024-01-15T10:30:00Z
# Resource    : s3_bucket
# Environment : prod
# Justification: Snapshot test request
# Module path : modules/s3_bucket
# Module ver  : 1.0.0
# =============================================================================
bucket_name = "mycompany-data-lake-prod"  # Name of the S3 bucket
environment = "prod"  # Deployment environment
tags = "{}"  # Additional tags for the bucket

# --- Security parameters (managed by Golden Module) ---
encryption_enabled = true  # Enable server-side encryption
versioning_enabled = true  # Enable versioning
