# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-sg-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : security_group
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/security_group
# Module ver  : 1.0.0
# =============================================================================
description = "Managed by Bedrock IaC Agent"  # Security group description
environment = "dev"  # Deployment environment
security_group_name = "mycompany-app-sg-dev"  # Name of the security group
vpc_id = "vpc-12345678"  # VPC ID to associate the security group with

# --- Security parameters (managed by Golden Module) ---
allow_all_ingress = false  # Deny all ingress by default
enable_flow_logs = true  # Enable flow logging for the security group
