# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-sns-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : sns_topic
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/sns_topic
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
fifo_topic = false  # Whether to create a FIFO topic
topic_name = "mycompany-alerts-dev"  # Name of the SNS topic

# --- Security parameters (managed by Golden Module) ---
encryption_enabled = true  # Enable server-side encryption
enforce_ssl = true  # Enforce SSL-only access
