# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-sqs-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : sqs_queue
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/sqs_queue
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
queue_name = "mycompany-job-queue-dev"  # Name of the SQS queue
visibility_timeout_seconds = 30  # Visibility timeout in seconds

# --- Security parameters (managed by Golden Module) ---
dead_letter_queue_enabled = true  # Enable dead letter queue
encryption_enabled = true  # Enable server-side encryption
