# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-vpc-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : vpc
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/vpc
# Module ver  : 1.0.0
# =============================================================================
availability_zones = "["a", "b", "c"]"  # Availability zones to use
cidr_block = "10.0.0.0/16"  # CIDR block for the VPC (e.g. 10.0.0.0/16)
environment = "dev"  # Deployment environment
vpc_name = "mycompany-main-dev"  # Name of the VPC

# --- Security parameters (managed by Golden Module) ---
enable_flow_logs = true  # Enable VPC flow logs
enable_network_acl = true  # Enable strict network ACLs
