# =============================================================================
# Generated by Bedrock IaC Agent
# DO NOT EDIT the security parameters — they are enforced by the Golden Module.
# =============================================================================
# Request ID  : req-vpc-dev
# Generated at: 2024-01-15T10:30:00Z
# Resource    : vpc
# Environment : dev
# Justification: Snapshot test request
# Module path : modules/vpc
# Module ver  : 1.0.0
# =============================================================================
environment = "dev"  # Deployment environment
name = "mycompany-main-dev"  # Name of the vpc
